version: "3"
services:
  server:
    env_file: .env
    restart: always
    build: .
    ports: 
      - '${APP_PORT}:3001'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  matomo:
    image: matomo
    restart: always
    volumes:
      - ./matomo/config:/var/www/html/config
      - ./matomo/logs:/var/www/html/logs
      - ./matomo/data:/var/www/html
    environment:
      - MYSQL_PASSWORD=viggodev
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=root
      - MATOMO_DATABASE_HOST="mysql://root:viggodev@10.83.19.104/matomo"
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_USERNAME=cesu
      - MATOMO_DATABASE_PASSWORD=1q2w3e4r
      - MATOMO_DATABASE_DBNAME=matomo
    ports:
      - 8087:80
